
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.appName }}
  labels:
    app: {{.Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.appName }}
  template:
    metadata:
      labels:
        app: {{.Values.appName }}
    spec:
      serviceAccountName: {{ .Values.appName }}
      containers:
      - name: server
        image: {{ .Values.image.repo }}/{{ .Values.image.repo }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8443
          name: tls
        - containerPort: 80
          name: metrics
        volumeMounts:
        - name: webhook-tls-certs
          mountPath: /etc/webhook/certs/
          readOnly: true
      volumes:
      - name: webhook-tls-certs
        secret:
          secretName: {{ include "mtwebhook.secretname" . }}