apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ template "mtwebhook.secretname" . }}
  labels:
    app: {{ template "mtwebhook.name" . }}
    chart: {{ template "mtwebhook.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
{{ ( include "mtwebhook.gen-certs" . ) | indent 2 }}