apiVersion: v1
kind: Service
metadata:
  name: {{.Values.appName }}
spec:
  selector:
    app: {{.Values.appName }}
  ports:
    - port: 443
      targetPort: tls
      name: application
    - port: 80
      targetPort: metrics
      name: metrics
