apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{.Values.appName }}
webhooks:
  - name: {{ template "mtwebhook.fqsvc" . }}.svc.cluster.local
    admissionReviewVersions:
      - "v1beta1"
    sideEffects: "None"
    timeoutSeconds: 30
    objectSelector:
      matchLabels:
        example-webhook-enabled: "true"
    clientConfig:
      service:
        name: {{.Values.appName }}
        namespace: {{ .Release.Namespace }}
        path: "/mutate"
      caBundle: |
        {{ ( lookup "v1" "Secret" .Release.Namespace (include "mtwebhook.secretname" .)).data.ca | b64enc }}
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]